trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip --output terraform.zip --silent
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Download Terraform v. 0.12'
